### ISSUE TITLE
Eval samples filtering

### ISSUE THREAD

**Issue by mutiann** [sanchit-gandhi/seq2seq-speech#77]
It seems that all the data are filtered by the input and label lengths in the current implementation, including eval samples, as in [the code](https://github.com/sanchit-gandhi/seq2seq-speech/blob/710d3bb9fe330f1129b1b81bbbbf905899398815/run_flax_speech_recognition_ctc.py#L1032).

Half of the eval samples for TEDLIUMv3 are not included in the evaluation as a result.

**Comment by sanchit-gandhi** [comment]
Entirely correct! Fixed in #84
